---
- hosts: azurevm
  become: true
  tasks:
    - name: Install Java 11 and Maven
      apt:
        pkg:
        - openjdk-11-jdk
        - maven
        update-cache: yes
        state: latest
        autoclean: yes
        autoremove: yes

    - name: Build and run FreePass
      ansible.builtin.shell:
        cmd: cd FreePass; mvn package -DskipTests; java -jar target/freepass-0.0.1-SNAPSHOT.jar